version: '3.8'
services:
 dynamodb-local:
  platform: linux/arm64
  command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  image: "amazon/dynamodb-local:latest"
  container_name: dynamodb-local
  ports:
    - "8000:8000"
  volumes:
    - "./docker/dynamodb:/home/dynamodblocal/data"
  working_dir: /home/dynamodblocal

 app-node:
  platform: linux/arm64
  image: justinpansacola/user:1.0
  container_name: user-app
  ports:
    - "8080:8080"
  depends_on:
    - "dynamodb-local"
  links:
    - "dynamodb-local"