# This is a basic workflow to help you get started with Actions

name: CI
# Add permissions for workflow
permissions:
  id-token: write
  contents: read
  pull-requests: read

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Get Current Pull Request
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - id: file_changes
        name: File Changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          prNumber: ${{ steps.pr.outputs.number }}
          pushBefore: ''
          pushAfter: ''
        
      - name: Ouput File Changes
        run: echo '${{ steps.file_changes.outputs.files }}'

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      # Runs a single command using the runners shell
      - name: Trigger admin-proxy workflow
        if: contains(steps.file_changes.outputs.files , 'admin-proxy/')
        working-directory: admin-proxy
        run: npm install && npm run test

      - name: Trigger frontend workflow
        if: contains(steps.file_changes.outputs.files , 'frontend/')
        working-directory: frontend
        run: echo Hello, frontend!
        
      - name: Trigger Maker-checker workflow
        if: contains(steps.file_changes.outputs.files , 'maker-checker/')
        working-directory: maker-checker
        run: echo Hello, maker-checker!
        
      - name: Trigger Points-ledger workflow
        if: contains(steps.file_changes.outputs.files , 'points-ledger/')
        working-directory: points-ledger
        run: echo Hello, points-ledger!
        
      - name: Trigger User workflow
        if: contains(steps.file_changes.outputs.files , 'User/')
        working-directory: User
        run: ./mvnw clean && ./mvnw test
