name: Run Frontend CD

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflow/frontend-cd.yaml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_FULL_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_S3_FULL_ACCESS_SECRET}}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Trigger Frontend Workflow
        working-directory: frontend
        run: |
          npm install
          NODE_ENV=production npm run build
          aws s3 sync ./dist/ s3://itsa-frontend --delete
